### ISSUE TITLE
Add to github API the ability to list assignees

### ISSUE THREAD

**Issue by htuch** [repokitteh/modules#23]
It's currently possible to list reviewers for PR with `github.pr_list_reviewers`. I think this maps to "request reviewers" in the GitHub API (please correct me if I'm wrong on this one). It would also be helpful, when writing a RK module that allows for automatic assignment of PRs to konw who the assignees are, i.e. we would need a `github.pr_list_assigness`.

**Comment by itayd** [comment]
you mean who the assignees on a specific pr right? not who can be assigned?

**Comment by itayd** [comment]
to get the assignees you don't really need a different function. since it's already in a pr context you can just specify `assignees` in the handler parameters and it will be populated with the logins for the assignees.

(i know better docs are in order here, will do)

/rk-ping

**Comment by itayd** [comment]
in the ping above you can see in the context there is no assignee.

/rk-ping

**Comment by itayd** [comment]
in the ping above you can see that i am assigned.
<img width="251" alt="Screen Shot 2020-10-10 at 10 39 46 PM" src="https://user-images.githubusercontent.com/426603/95671256-82359580-0b49-11eb-9bc2-17253cb10900.png">

**Comment by itayd** [comment]
huh, not sure why assignees is empty. also assignee shows only a single assignee. checking.

**Comment by itayd** [comment]
found the issue, working on a fix.

**Comment by itayd** [comment]
should be fixed now.

/rk-ping

**Comment by itayd** [comment]
yup! working.

**Comment by htuch** [comment]
@itayd I might be a bit dense here, but I'm not following how to get at this from somewhere like the `_pr` handler in https://github.com/envoyproxy/envoy/blob/07776d77403fd3ae97eefcfca7645de45a3ab628/ci/repokitteh/modules/ownerscheck.star#L236. Could you provide a hint or some reference example? Thanks.

**Comment by itayd** [comment]
In https://github.com/envoyproxy/envoy/blob/07776d77403fd3ae97eefcfca7645de45a3ab628/ci/repokitteh/modules/ownerscheck.star#L200, just add another parameter: `assignees`.
