### ISSUE TITLE
github.call doesnt seem to allow `...` in the path

### ISSUE THREAD

**Issue by phlax** [repokitteh/modules#28]
in order to use the comparison api you need to be able to separate the hashes with `...`

this seems to throw a `Error: function _rk_error error: path contains forbidden characters`

**Comment by itayd** [comment]
what api are you using exactly?

**Comment by itayd** [comment]
i guess it is https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#compare-two-commits

**Comment by itayd** [comment]
fixed. also added https://www.repokitteh.io/docs/ref/modules/#github.compare_commits. will deploy shortly.

**Comment by itayd** [comment]
deployed.
